
import { Language, TranslationSet } from './types';

export const TRANSLATIONS: Record<Language, TranslationSet> = {
  English: {
    app_title: "Saif-AI Defense Core",
    sidebar_subtitle: "UAE Cyber-Shield v3.5",
    tab_image: "SCAN EVIDENCE",
    tab_text: "ANALYZE TEXT",
    upload_text: "Drop suspicious screenshot here",
    text_input_placeholder: "Paste suspicious message content...",
    analyze_btn: "INITIATE DIAGNOSTIC",
    investigating: "RUNNING FORENSICS...",
    threat_detected: "⚠️ THREAT DETECTED",
    safe_verdict: "✅ VERIFIED SAFE",
    error_high_traffic: "⚠️ Node Busy - Retrying...",
    police_report_label: "AL AMEEN REPORT DRAFT",
    send_sms_btn: "OPEN SMS APP",
    copy_btn: "COPY TEXT",
    select_lang_label: "SYSTEM LANGUAGE",
    disclaimer: "AI Reference Only. For Emergencies Call 999.",
    nav_scanner: "Threat Scanner",
    nav_map: "Live Threat Map",
    nav_voice: "Voice Defense",
    nav_gov: "Gov-ID Verify",
    nav_delivery: "Delivery Shield",
    nav_training: "Cyber Training",
    map_title: "Active Threat Heatmap",
    voice_status: "Voice Guard: LISTENING",
    gov_status: "Official Portal Verification",
    delivery_title: "Logistics Fraud Detection",
    training_title: "Agent Training Simulator",
    tactical_analysis: "Tactical Analysis",
    risk_score_label: "RISK SCORE",
    landing_title: "SECURE YOUR DIGITAL LIFE",
    landing_subtitle: "Advanced AI protection against fraud, phishing, and identity theft in the UAE.",
    landing_cta: "INITIALIZE SYSTEM",
    live_stat_1: "THREATS BLOCKED TODAY",
    live_stat_2: "ACTIVE NODES",
    police_section: "OFFICIAL SUPPORT",
    call_police: "Call 901 (Non-Emergency)",
    email_police: "Report Cyber Crime"
  },
  Arabic: {
    app_title: "نظام سيف للدفاع الرقمي",
    sidebar_subtitle: "درع الأمن السيبراني v3.5",
    tab_image: "فحص الأدلة",
    tab_text: "تحليل النص",
    upload_text: "ارفق لقطة الشاشة هنا",
    text_input_placeholder: "الصق نص الرسالة هنا...",
    analyze_btn: "بدء الفحص",
    investigating: "جاري التحليل الجنائي...",
    threat_detected: "⚠️ تم رصد تهديد",
    safe_verdict: "✅ آمن وموثق",
    error_high_traffic: "⚠️ النظام مشغول - المحاولة...",
    police_report_label: "تقرير الأمين",
    send_sms_btn: "فتح الرسائل",
    copy_btn: "نسخ النص",
    select_lang_label: "لغة النظام",
    disclaimer: "للمرجعية فقط. للطوارئ 999.",
    nav_scanner: "ماسح التهديدات",
    nav_map: "خريطة التهديدات",
    nav_voice: "حارس الصوت",
    nav_gov: "توثيق الهوية",
    nav_delivery: "درع التوصيل",
    nav_training: "تدريب العملاء",
    map_title: "خريطة الاحتيال المباشرة",
    voice_status: "حارس الصوت: يراقب",
    gov_status: "توثيق البوابات الحكومية",
    delivery_title: "كشف احتيال التوصيل",
    training_title: "محاكي التدريب",
    tactical_analysis: "التحليل التكتيكي",
    risk_score_label: "درجة المخاطر",
    landing_title: "حصن حياتك الرقمية",
    landing_subtitle: "حماية متقدمة بالذكاء الاصطناعي ضد الاحتيال وسرقة الهوية في الإمارات.",
    landing_cta: "تفعيل النظام",
    live_stat_1: "تهديدات تم حظرها اليوم",
    live_stat_2: "نقاط نشطة",
    police_section: "الدعم الرسمي",
    call_police: "اتصل بـ 901 (غير الطوارئ)",
    email_police: "بلغ عن الجرائم الإلكترونية"
  },
  Hindi: {
    app_title: "Saif-AI डिफेंस कोर",
    sidebar_subtitle: "UAE Cyber-Shield v3.5",
    tab_image: "स्कैन सबूत",
    tab_text: "टेक्स्ट विश्लेषण",
    upload_text: "स्क्रीनशॉट यहाँ डालें",
    text_input_placeholder: "संदिग्ध संदेश यहाँ पेस्ट करें...",
    analyze_btn: "जांच शुरू करें",
    investigating: "विश्लेषण चल रहा है...",
    threat_detected: "⚠️ खतरा मिला",
    safe_verdict: "✅ सुरक्षित",
    error_high_traffic: "⚠️ सिस्टम व्यस्त",
    police_report_label: "पुलिस रिपोर्ट ड्राफ्ट",
    send_sms_btn: "SMS ऐप खोलें",
    copy_btn: "टेक्स्ट कॉपी करें",
    select_lang_label: "सिस्टम भाषा",
    disclaimer: "केवल संदर्भ के लिए।",
    nav_scanner: "थ्रेट स्कैनर",
    nav_map: "लाइव मैप",
    nav_voice: "वॉयस गार्ड",
    nav_gov: "Gov-ID वेरीफायर",
    nav_delivery: "डिलीवरी शील्ड",
    nav_training: "साइबर ट्रेनिंग",
    map_title: "सक्रिय खतरा हीटमैप",
    voice_status: "वॉयस गार्ड: निगरानी",
    gov_status: "Gov-ID सत्यापन",
    delivery_title: "डिलीवरी धोखाधड़ी जांच",
    training_title: "एजेंट ट्रेनिंग",
    tactical_analysis: "विस्तृत विश्लेषण",
    risk_score_label: "जोखिम स्कोर",
    landing_title: "अपनी डिजिटल दुनिया सुरक्षित करें",
    landing_subtitle: "UAE में धोखाधड़ी और पहचान की चोरी के खिलाफ उन्नत AI सुरक्षा।",
    landing_cta: "सिस्टम शुरू करें",
    live_stat_1: "आज ब्लॉक किए गए खतरे",
    live_stat_2: "सक्रिय नोड्स",
    police_section: "आधिकारिक सहायता",
    call_police: "901 पर कॉल करें",
    email_police: "साइबर अपराध रिपोर्ट करें"
  },
  Urdu: {
    app_title: "Saif-AI ڈیفنس کور",
    sidebar_subtitle: "UAE Cyber-Shield v3.5",
    tab_image: "ثبوت اسکین کریں",
    tab_text: "متن کا تجزیہ",
    upload_text: "اسکرین شاٹ یہاں رکھیں",
    text_input_placeholder: "پیغام یہاں پیسٹ کریں...",
    analyze_btn: "تجزیہ شروع کریں",
    investigating: "تفتیش جاری ہے...",
    threat_detected: "⚠️ خطرہ",
    safe_verdict: "✅ محفوظ",
    error_high_traffic: "⚠️ سسٹم مصروف",
    police_report_label: "پولیس رپورٹ",
    send_sms_btn: "SMS کھولیں",
    copy_btn: "کاپی کریں",
    select_lang_label: "سسٹم کی زبان",
    disclaimer: "صرف حوالہ کے لیے۔",
    nav_scanner: "اسکینر",
    nav_map: "لائیو میپ",
    nav_voice: "وائس گارڈ",
    nav_gov: "Gov-ID تصدیق",
    nav_delivery: "ڈیلیوری شیلڈ",
    nav_training: "سائبر ٹریننگ",
    map_title: "لائیو تھریٹ میپ",
    voice_status: "وائس گارڈ: نگرانی",
    gov_status: "سرکاری تصدیق",
    delivery_title: "ڈیلیوری فراڈ چیک",
    training_title: "ایجنٹ ٹریننگ",
    tactical_analysis: "تفصیلی تجزیہ",
    risk_score_label: "رسک اسکور",
    landing_title: "اپنی ڈیجیٹل زندگی محفوظ بنائیں",
    landing_subtitle: "UAE میں دھوکہ دہی کے خلاف جدید AI تحفظ۔",
    landing_cta: "سسٹم شروع کریں",
    live_stat_1: "آج بلاک کیے گئے خطرات",
    live_stat_2: "فعال نوڈس",
    police_section: "سرکاری مدد",
    call_police: "901 پر کال کریں",
    email_police: "رپورٹ کریں"
  },
  Tagalog: {
    app_title: "Saif-AI Defense Core",
    sidebar_subtitle: "UAE Cyber-Shield v3.5",
    tab_image: "I-SCAN ANG EBIDENSYA",
    tab_text: "SURIIN ANG TEKSTO",
    upload_text: "I-upload ang screenshot",
    text_input_placeholder: "I-paste ang mensahe...",
    analyze_btn: "SIMULAN ANG PAGSUSURI",
    investigating: "NAGSASAGAWA NG FORENSICS...",
    threat_detected: "⚠️ MAY BANTA",
    safe_verdict: "✅ LIGTAS",
    error_high_traffic: "⚠️ Busy ang System",
    police_report_label: "DRAFT NG REPORT",
    send_sms_btn: "BUKSAN ANG SMS",
    copy_btn: "KOPYAHIN",
    select_lang_label: "Wika ng System",
    disclaimer: "Gabay lamang.",
    nav_scanner: "Scanner",
    nav_map: "Live Map",
    nav_voice: "Voice Defense",
    nav_gov: "Gov-ID Verify",
    nav_delivery: "Delivery Shield",
    nav_training: "Cyber Training",
    map_title: "Active Threat Heatmap",
    voice_status: "Voice Guard: LISTENING",
    gov_status: "Gov-ID Verification",
    delivery_title: "Logistics Fraud Detection",
    training_title: "Pagsasanay ng Agent",
    tactical_analysis: "Pagsusuri ng Taktika",
    risk_score_label: "RISK SCORE",
    landing_title: "PROTEKTAHAN ANG IYONG DIGITAL NA BUHAY",
    landing_subtitle: "Advanced na AI proteksyon laban sa panloloko sa UAE.",
    landing_cta: "SIMULAN ANG SYSTEM",
    live_stat_1: "NA-BLOCK NA BANTA NGAYON",
    live_stat_2: "AKTIBONG NODES",
    police_section: "OPISYAL NA SUPORTA",
    call_police: "Tumawag sa 901",
    email_police: "I-report ang Cyber Crime"
  }
};

export const LANGUAGES: Language[] = ['English', 'Arabic', 'Hindi', 'Urdu', 'Tagalog'];
